config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/index'
  get 'users/logout'
  get 'users/account_locked'
  post 'users/login'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :handle, presence: true, uniqueness: true
  validates :password, presence: true
  validates_inclusion_of :login_count, in: [nil, 0, 1, 2, 3]

  def self.login(params)
    user = User.where(handle: params[:handle]).first
    login_count = user&.login_count
    if user && login_count.to_i < 3
      login_count = if user&.password == params[:password]
                      0
                    else
                      login_count.to_i + 1
                    end
      user.login_count = login_count
      user.save
    end

    login_count
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def login
    login_count = User.login(params)
    if !login_count
      redirect_to '/users/index'
    elsif login_count.to_i.zero?
      redirect_to '/users/logout'
    elsif login_count.to_i > 2
      redirect_to '/users/account_locked'
    else
      redirect_to '/users/index'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MullenChrisLongboat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/account_locked.html.erb
<h1>Account Locked</h1>
<%= link_to 'login with a new account', 'index' %>

app/views/users/index.html.erb
<h1>Login</h1>
<%= form_with url: users_login_path do |f| %>
  <table>
    <tr>
      <td><%= f.label 'Handle' %></td>
      <td><%= f.text_field :handle %></td>
    </tr>
    <tr>
      <td><%= f.label 'Password' %></td>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <td><%= f.submit 'Login' %></td>
    </tr>
  </table>
<% end %>

app/views/users/logout.html.erb
<h1>You are logged in</h1>
<%= link_to 'logout', 'index' %>